//
//  NotificationInboxStore.swift
//  mushroomHunter
//
//  Purpose:
//  - Stores and paginates user notification events from Firestore.
//
//  Defined in this file:
//  - NotificationInboxStore, NotificationInboxItem, and NotificationInboxRoute models.
//
import Foundation
import Combine
import FirebaseAuth
import FirebaseFirestore

/// Deep-link route metadata attached to one inbox notification row.
struct NotificationInboxRoute: Codable, Equatable {
    /// Destination category used by the inbox open action.
    enum Kind: String, Codable {
        /// Opens a room detail destination.
        case room
        /// Opens a postcard detail destination.
        case postcard
        /// No destination available for this notification.
        case none
    }

    /// Destination category.
    let kind: Kind
    /// Target room id when `kind == .room`.
    let roomId: String?
    /// Target postcard id when `kind == .postcard`.
    let postcardId: String?
    /// Optional order id attached to postcard-order routes.
    let orderId: String?
    /// True when route should open room confirmation queue immediately.
    let isOpeningConfirmationQueue: Bool
    /// True when route should open postcard order context immediately.
    let isOpeningOrderPage: Bool
}

/// One Firestore-backed inbox event row.
struct NotificationInboxItem: Identifiable, Codable, Equatable {
    /// Stable document id for list rendering and read-state updates.
    let id: String
    /// Event type value generated by backend workflow.
    let type: String
    /// User-facing message title.
    let title: String
    /// User-facing message body.
    let message: String
    /// Event creation timestamp.
    let receivedAt: Date
    /// True when this event requires explicit user action.
    let isActionEvent: Bool
    /// True when this event has already been resolved/processed.
    var isResolved: Bool
    /// Destination route metadata used by tap navigation.
    let route: NotificationInboxRoute
}

/// Shared notification inbox state and Firestore paging bridge.
@MainActor
final class NotificationInboxStore: ObservableObject {
    /// Shared singleton used by both AppDelegate and SwiftUI views.
    static let shared = NotificationInboxStore()

    /// Latest inbox rows (newest first).
    @Published private(set) var items: [NotificationInboxItem] = []
    /// True while first page is being loaded.
    @Published private(set) var isLoadingInitialPage: Bool = false
    /// True while next page is being loaded.
    @Published private(set) var isLoadingNextPage: Bool = false
    /// True when backend likely has another page.
    @Published private(set) var isHasMorePages: Bool = false

    /// Firestore database reference used for inbox paging and read updates.
    private let db = Firestore.firestore()
    /// Firebase auth-state listener that keeps user-scoped inbox state in sync.
    private var authHandle: AuthStateDidChangeListenerHandle?
    /// Current signed-in uid used for user-scoped queries.
    private var currentUserId: String? = nil
    /// Last page cursor used by incremental pagination.
    private var lastDocumentCursor: QueryDocumentSnapshot? = nil
    /// Number of events loaded per page.
    private let pageSize: Int = 10

    /// Initializes auth synchronization and clears state until a user is signed in.
    private init() {
        authHandle = Auth.auth().addStateDidChangeListener { [weak self] _, user in
            guard let self else { return }
            Task { @MainActor in
                self.handleAuthStateDidChange(userId: user?.uid)
            }
        }
    }

    deinit {
        if let authHandle {
            Auth.auth().removeStateDidChangeListener(authHandle)
        }
    }

    /// Count of unresolved action events currently loaded in memory.
    var unreadCount: Int {
        items.reduce(0) { partialCount, item in
            partialCount + (item.isActionEvent && item.isResolved == false ? 1 : 0)
        }
    }

    /// Forces latest page refresh from Firestore.
    func refreshFromServer() async {
        guard let currentUserId, currentUserId.isEmpty == false else {
            resetState()
            return
        }
        guard isLoadingInitialPage == false else { return }

        isLoadingInitialPage = true
        defer { isLoadingInitialPage = false }

        do {
            let pageSnapshot = try await fetchPage(userId: currentUserId, after: nil)
            let loadedItems = pageSnapshot.documents.map(decodeItem)
            items = loadedItems
            lastDocumentCursor = pageSnapshot.documents.last
            isHasMorePages = pageSnapshot.documents.count == pageSize
        } catch {
            // Keep current in-memory rows if refresh fails.
        }
    }

    /// Loads one older page when user scrolls near the end of current list.
    /// - Parameter currentItemId: Row id that just appeared on screen.
    func loadNextPageIfNeeded(currentItemId: String) {
        guard let lastItemId = items.last?.id else { return }
        guard lastItemId == currentItemId else { return }
        guard isLoadingInitialPage == false else { return }
        guard isLoadingNextPage == false else { return }
        guard isHasMorePages else { return }
        guard let currentUserId, currentUserId.isEmpty == false else { return }

        Task {
            await loadNextPage(userId: currentUserId)
        }
    }

    /// Handles push receive events by syncing latest rows from server.
    /// - Parameters:
    ///   - userInfo: APNs custom payload dictionary.
    ///   - title: Notification title from APNs content.
    ///   - message: Notification body from APNs content.
    func appendPushNotification(
        userInfo: [AnyHashable: Any],
        title: String,
        message: String
    ) {
        let type = (userInfo["type"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let _ = title
        let _ = message

        // Action events must force-refresh so the badge count stays accurate.
        guard isActionEventType(type: type) else { return }
        Task {
            await refreshFromServer()
        }
    }

    /// Updates in-memory inbox when auth user changes.
    /// - Parameter userId: Current Firebase auth uid, if any.
    private func handleAuthStateDidChange(userId: String?) {
        if currentUserId != userId {
            currentUserId = userId
            resetState()
        }
    }

    /// Resets in-memory paging state for sign-out/user-switch events.
    private func resetState() {
        items = []
        lastDocumentCursor = nil
        isHasMorePages = false
        isLoadingInitialPage = false
        isLoadingNextPage = false
    }

    /// Loads one paged slice from Firestore for a user inbox collection.
    /// - Parameters:
    ///   - userId: Target user uid.
    ///   - cursor: Optional cursor for pagination.
    /// - Returns: Firestore query snapshot for one page.
    private func fetchPage(userId: String, after cursor: QueryDocumentSnapshot?) async throws -> QuerySnapshot {
        var query: Query = db.collection("users")
            .document(userId)
            .collection("events")
            .order(by: "createdAt", descending: true)
            .limit(to: pageSize)

        if let cursor {
            query = query.start(afterDocument: cursor)
        }

        do {
            return try await query.getDocuments(source: .server)
        } catch {
            return try await query.getDocuments(source: .default)
        }
    }

    /// Loads and appends one older page of inbox events.
    /// - Parameter userId: Current signed-in uid.
    private func loadNextPage(userId: String) async {
        guard let cursor = lastDocumentCursor else {
            isHasMorePages = false
            return
        }

        isLoadingNextPage = true
        defer { isLoadingNextPage = false }

        do {
            let pageSnapshot = try await fetchPage(userId: userId, after: cursor)
            let loadedItems = pageSnapshot.documents.map(decodeItem)
            appendUnique(items: loadedItems)
            lastDocumentCursor = pageSnapshot.documents.last ?? lastDocumentCursor
            isHasMorePages = pageSnapshot.documents.count == pageSize
        } catch {
            // Keep existing list if loading older page fails.
        }
    }

    /// Appends page items while preserving stable event id uniqueness.
    /// - Parameter items: Older page rows to append.
    private func appendUnique(items incomingItems: [NotificationInboxItem]) {
        guard incomingItems.isEmpty == false else { return }
        let existingIds = Set(items.map(\.id))
        let filteredItems = incomingItems.filter { existingIds.contains($0.id) == false }
        items.append(contentsOf: filteredItems)
    }

    /// Decodes Firestore notification document into inbox row model.
    /// - Parameter document: Firestore event document.
    /// - Returns: Decoded inbox row.
    private func decodeItem(_ document: QueryDocumentSnapshot) -> NotificationInboxItem {
        let data = document.data()

        let type = (data["type"] as? String ?? "unknown")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let storedTitle = (data["title"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let storedMessage = (data["message"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let title = storedTitle.isEmpty ? localizedEventTitle(type: type) : storedTitle
        let message = storedMessage.isEmpty ? localizedEventMessage(type: type) : storedMessage
        let receivedAt = (data["createdAt"] as? Timestamp)?.dateValue() ?? Date()
        let isActionEvent = data["isActionEvent"] as? Bool ?? isActionEventType(type: type)
        let isResolved = data["isResolved"] as? Bool ?? !isActionEvent

        let route = resolveRouteFromData(
            data: data,
            fallbackType: type,
            isActionEvent: isActionEvent
        )

        return NotificationInboxItem(
            id: document.documentID,
            type: type.isEmpty ? "unknown" : type,
            title: title,
            message: message,
            receivedAt: receivedAt,
            isActionEvent: isActionEvent,
            isResolved: isResolved,
            route: route
        )
    }

    /// Resolves localized title text from event type.
    /// - Parameter type: Event type payload value.
    /// - Returns: Localized title text.
    private func localizedEventTitle(type: String) -> String {
        let localizedKey = "event_type_\(type)_title"
        let localizedValue = NSLocalizedString(localizedKey, comment: "")
        if localizedValue != localizedKey {
            return localizedValue
        }
        return NSLocalizedString("notification_default_title", comment: "")
    }

    /// Resolves localized message text from event type.
    /// - Parameter type: Event type payload value.
    /// - Returns: Localized message text.
    private func localizedEventMessage(type: String) -> String {
        let localizedKey = "event_type_\(type)_message"
        let localizedValue = NSLocalizedString(localizedKey, comment: "")
        if localizedValue != localizedKey {
            return localizedValue
        }
        return type.replacingOccurrences(of: "_", with: " ")
    }

    /// Parses route metadata persisted in Firestore and falls back to type-based inference.
    /// - Parameters:
    ///   - data: Firestore event document data.
    ///   - fallbackType: Event type used by fallback resolver.
    /// - Returns: Resolved deep-link route.
    private func resolveRouteFromData(
        data: [String: Any],
        fallbackType: String,
        isActionEvent: Bool
    ) -> NotificationInboxRoute {
        if isActionEvent == false {
            return NotificationInboxRoute(
                kind: .none,
                roomId: nil,
                postcardId: nil,
                orderId: nil,
                isOpeningConfirmationQueue: false,
                isOpeningOrderPage: false
            )
        }

        let roomId = (data["roomId"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let postcardId = (data["postcardId"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let orderId = (data["orderId"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)

        return resolveFallbackRoute(
            type: fallbackType,
            roomId: roomId.isEmpty ? nil : roomId,
            postcardId: postcardId.isEmpty ? nil : postcardId,
            orderId: orderId.isEmpty ? nil : orderId
        )
    }

    /// Resolves whether one event type is treated as Action Event.
    /// - Parameter type: Event type payload value.
    /// - Returns: True when this event requires explicit user action.
    private func isActionEventType(type: String) -> Bool {
        switch type {
        case "RAID_CONFIRM_ATTENDEE", "JOIN_REQUESTED_HOST", "POSTCARD_ORDER_SELLER", "POSTCARD_SENT_BUYER":
            return true
        default:
            return false
        }
    }

    /// Fallback route mapping used when backend route fields are absent.
    /// - Parameters:
    ///   - type: Event type payload value.
    ///   - roomId: Parsed room id if present.
    ///   - postcardId: Parsed postcard id if present.
    ///   - orderId: Parsed order id if present.
    /// - Returns: Best-effort route metadata.
    private func resolveFallbackRoute(
        type: String,
        roomId: String?,
        postcardId: String?,
        orderId: String?
    ) -> NotificationInboxRoute {
        if let roomId, roomId.isEmpty == false {
            return NotificationInboxRoute(
                kind: .room,
                roomId: roomId,
                postcardId: nil,
                orderId: nil,
                isOpeningConfirmationQueue: type == "RAID_CONFIRM_ATTENDEE",
                isOpeningOrderPage: false
            )
        }

        if let postcardId, postcardId.isEmpty == false {
            return NotificationInboxRoute(
                kind: .postcard,
                roomId: nil,
                postcardId: postcardId,
                orderId: orderId,
                isOpeningConfirmationQueue: false,
                isOpeningOrderPage: type == "POSTCARD_ORDER_SELLER" || type == "POSTCARD_SENT_BUYER"
            )
        }

        return NotificationInboxRoute(
            kind: .none,
            roomId: nil,
            postcardId: nil,
            orderId: nil,
            isOpeningConfirmationQueue: false,
            isOpeningOrderPage: false
        )
    }

}
