//
//  NotificationInboxStore.swift
//  mushroomHunter
//
//  Purpose:
//  - Stores and paginates user notification events from Firestore.
//
//  Defined in this file:
//  - NotificationInboxStore, NotificationInboxItem, and NotificationInboxRoute models.
//
import Foundation
import Combine
import FirebaseAuth
import FirebaseFirestore

/// Deep-link route metadata attached to one inbox notification row.
struct NotificationInboxRoute: Codable, Equatable {
    /// Destination category used by the inbox open action.
    enum Kind: String, Codable {
        /// Opens a room detail destination.
        case room
        /// Opens a postcard detail destination.
        case postcard
        /// No destination available for this notification.
        case none
    }

    /// Destination category.
    let kind: Kind
    /// Target room id when `kind == .room`.
    let roomId: String?
    /// Target postcard id when `kind == .postcard`.
    let postcardId: String?
    /// Optional order id attached to postcard-order routes.
    let orderId: String?
    /// True when route should open room confirmation queue immediately.
    let isOpeningConfirmationQueue: Bool
    /// True when route should open postcard order context immediately.
    let isOpeningOrderPage: Bool
}

/// One Firestore-backed inbox event row.
struct NotificationInboxItem: Identifiable, Codable, Equatable {
    /// Stable document id for list rendering and read-state updates.
    let id: String
    /// Event type value generated by backend workflow.
    let type: String
    /// User-facing message title.
    let title: String
    /// User-facing message body.
    let message: String
    /// Event creation timestamp.
    let receivedAt: Date
    /// True when this message has already been opened/read.
    var isRead: Bool
    /// Destination route metadata used by tap navigation.
    let route: NotificationInboxRoute
}

/// Shared notification inbox state and Firestore paging bridge.
@MainActor
final class NotificationInboxStore: ObservableObject {
    /// Shared singleton used by both AppDelegate and SwiftUI views.
    static let shared = NotificationInboxStore()

    /// Latest inbox rows (newest first).
    @Published private(set) var items: [NotificationInboxItem] = []
    /// True while first page is being loaded.
    @Published private(set) var isLoadingInitialPage: Bool = false
    /// True while next page is being loaded.
    @Published private(set) var isLoadingNextPage: Bool = false
    /// True when backend likely has another page.
    @Published private(set) var isHasMorePages: Bool = false

    /// Firestore database reference used for inbox paging and read updates.
    private let db = Firestore.firestore()
    /// Firebase auth-state listener that keeps user-scoped inbox state in sync.
    private var authHandle: AuthStateDidChangeListenerHandle?
    /// Current signed-in uid used for user-scoped queries.
    private var currentUserId: String? = nil
    /// Last page cursor used by incremental pagination.
    private var lastDocumentCursor: QueryDocumentSnapshot? = nil
    /// Number of events loaded per page.
    private let pageSize: Int = 10

    /// Initializes auth synchronization and clears state until a user is signed in.
    private init() {
        authHandle = Auth.auth().addStateDidChangeListener { [weak self] _, user in
            guard let self else { return }
            Task { @MainActor in
                self.handleAuthStateDidChange(userId: user?.uid)
            }
        }
    }

    deinit {
        if let authHandle {
            Auth.auth().removeStateDidChangeListener(authHandle)
        }
    }

    /// Count of unread inbox rows currently loaded in memory.
    var unreadCount: Int {
        items.reduce(0) { partialCount, item in
            partialCount + (item.isRead ? 0 : 1)
        }
    }

    /// Loads first page (latest 10 events) when inbox opens.
    func loadInitialPageIfNeeded() {
        guard items.isEmpty else { return }
        Task {
            await refreshFromServer()
        }
    }

    /// Forces latest page refresh from Firestore.
    func refreshFromServer() async {
        guard let currentUserId, currentUserId.isEmpty == false else {
            resetState()
            return
        }
        guard isLoadingInitialPage == false else { return }

        isLoadingInitialPage = true
        defer { isLoadingInitialPage = false }

        do {
            let pageSnapshot = try await fetchPage(userId: currentUserId, after: nil)
            let loadedItems = pageSnapshot.documents.map(decodeItem)
            items = loadedItems
            lastDocumentCursor = pageSnapshot.documents.last
            isHasMorePages = pageSnapshot.documents.count == pageSize
        } catch {
            // Keep current in-memory rows if refresh fails.
        }
    }

    /// Loads one older page when user scrolls near the end of current list.
    /// - Parameter currentItemId: Row id that just appeared on screen.
    func loadNextPageIfNeeded(currentItemId: String) {
        guard let lastItemId = items.last?.id else { return }
        guard lastItemId == currentItemId else { return }
        guard isLoadingInitialPage == false else { return }
        guard isLoadingNextPage == false else { return }
        guard isHasMorePages else { return }
        guard let currentUserId, currentUserId.isEmpty == false else { return }

        Task {
            await loadNextPage(userId: currentUserId)
        }
    }

    /// Marks one inbox row as read.
    /// - Parameter itemId: Target event document id.
    func markAsRead(itemId: String) {
        guard let index = items.firstIndex(where: { $0.id == itemId }) else { return }
        guard items[index].isRead == false else { return }
        items[index].isRead = true

        Task {
            await updateReadState(itemId: itemId, isRead: true)
        }
    }

    /// Marks all currently loaded inbox rows as read.
    func markAllAsRead() {
        let unreadIds = items.filter { $0.isRead == false }.map(\.id)
        guard unreadIds.isEmpty == false else { return }

        for index in items.indices {
            items[index].isRead = true
        }

        Task {
            await markItemsAsRead(itemIds: unreadIds)
        }
    }

    /// Handles push receive events by syncing latest rows from server and optionally marking one row as read.
    /// - Parameters:
    ///   - userInfo: APNs custom payload dictionary.
    ///   - title: Notification title from APNs content.
    ///   - message: Notification body from APNs content.
    ///   - isRead: True when this event should be marked as already read.
    func appendPushNotification(
        userInfo: [AnyHashable: Any],
        title: String,
        message: String,
        isRead: Bool
    ) {
        let _ = title
        let _ = message

        if isRead,
           let eventId = resolvedStringValue(from: userInfo, primaryKey: "eventId", secondaryKey: "event_id"),
           eventId.isEmpty == false {
            Task {
                await updateReadState(itemId: eventId, isRead: true)
            }
        }

        Task {
            await refreshFromServer()
        }
    }

    /// Updates in-memory inbox when auth user changes.
    /// - Parameter userId: Current Firebase auth uid, if any.
    private func handleAuthStateDidChange(userId: String?) {
        if currentUserId != userId {
            currentUserId = userId
            resetState()
        }
        guard userId?.isEmpty == false else { return }
        Task {
            await refreshFromServer()
        }
    }

    /// Resets in-memory paging state for sign-out/user-switch events.
    private func resetState() {
        items = []
        lastDocumentCursor = nil
        isHasMorePages = false
        isLoadingInitialPage = false
        isLoadingNextPage = false
    }

    /// Loads one paged slice from Firestore for a user inbox collection.
    /// - Parameters:
    ///   - userId: Target user uid.
    ///   - cursor: Optional cursor for pagination.
    /// - Returns: Firestore query snapshot for one page.
    private func fetchPage(userId: String, after cursor: QueryDocumentSnapshot?) async throws -> QuerySnapshot {
        var query: Query = db.collection("users")
            .document(userId)
            .collection("events")
            .order(by: "createdAt", descending: true)
            .limit(to: pageSize)

        if let cursor {
            query = query.start(afterDocument: cursor)
        }

        do {
            return try await query.getDocuments(source: .server)
        } catch {
            return try await query.getDocuments(source: .default)
        }
    }

    /// Loads and appends one older page of inbox events.
    /// - Parameter userId: Current signed-in uid.
    private func loadNextPage(userId: String) async {
        guard let cursor = lastDocumentCursor else {
            isHasMorePages = false
            return
        }

        isLoadingNextPage = true
        defer { isLoadingNextPage = false }

        do {
            let pageSnapshot = try await fetchPage(userId: userId, after: cursor)
            let loadedItems = pageSnapshot.documents.map(decodeItem)
            appendUnique(items: loadedItems)
            lastDocumentCursor = pageSnapshot.documents.last ?? lastDocumentCursor
            isHasMorePages = pageSnapshot.documents.count == pageSize
        } catch {
            // Keep existing list if loading older page fails.
        }
    }

    /// Appends page items while preserving stable event id uniqueness.
    /// - Parameter items: Older page rows to append.
    private func appendUnique(items incomingItems: [NotificationInboxItem]) {
        guard incomingItems.isEmpty == false else { return }
        let existingIds = Set(items.map(\.id))
        let filteredItems = incomingItems.filter { existingIds.contains($0.id) == false }
        items.append(contentsOf: filteredItems)
    }

    /// Decodes Firestore notification document into inbox row model.
    /// - Parameter document: Firestore event document.
    /// - Returns: Decoded inbox row.
    private func decodeItem(_ document: QueryDocumentSnapshot) -> NotificationInboxItem {
        let data = document.data()

        let type = (data["type"] as? String ?? "unknown")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let fallbackTitle = (data["title"] as? String ?? NSLocalizedString("notification_default_title", comment: ""))
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let fallbackMessage = (data["message"] as? String ?? "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let title = localizedEventText(
            key: data["titleLocKey"] as? String,
            rawArgs: data["titleLocArgs"] as? [Any],
            fallback: fallbackTitle
        )
        let message = localizedEventText(
            key: data["messageLocKey"] as? String,
            rawArgs: data["messageLocArgs"] as? [Any],
            fallback: fallbackMessage
        )
        let receivedAt = (data["createdAt"] as? Timestamp)?.dateValue() ?? Date()
        let isRead = data["isRead"] as? Bool ?? false

        let route = resolveRouteFromData(data: data, fallbackType: type)

        return NotificationInboxItem(
            id: document.documentID,
            type: type.isEmpty ? "unknown" : type,
            title: title.isEmpty ? NSLocalizedString("notification_default_title", comment: "") : title,
            message: message.isEmpty ? type : message,
            receivedAt: receivedAt,
            isRead: isRead,
            route: route
        )
    }

    /// Resolves one localized event string using a key and `%@`/`%d` style argument list.
    /// - Parameters:
    ///   - key: Localizable-string key persisted in event payload.
    ///   - rawArgs: Dynamic argument list persisted in event payload.
    ///   - fallback: Fallback plain text when key/format resolution fails.
    /// - Returns: Localized formatted text for current app language.
    private func localizedEventText(
        key: String?,
        rawArgs: [Any]?,
        fallback: String
    ) -> String {
        let trimmedKey = (key ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedKey.isEmpty {
            return fallback
        }

        let format = NSLocalizedString(trimmedKey, comment: "")
        if format == trimmedKey {
            return fallback
        }

        let args: [CVarArg] = (rawArgs ?? []).map { value in
            String(describing: value) as CVarArg
        }
        if args.isEmpty {
            return format
        }
        return String(format: format, locale: Locale.current, arguments: args)
    }

    /// Parses route metadata persisted in Firestore and falls back to type-based inference.
    /// - Parameters:
    ///   - data: Firestore event document data.
    ///   - fallbackType: Event type used by fallback resolver.
    /// - Returns: Resolved deep-link route.
    private func resolveRouteFromData(data: [String: Any], fallbackType: String) -> NotificationInboxRoute {
        let routeKindRaw = (data["routeKind"] as? String ?? "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        let roomId = (data["roomId"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let postcardId = (data["postcardId"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        let orderId = (data["orderId"] as? String ?? "").trimmingCharacters(in: .whitespacesAndNewlines)

        let isOpeningConfirmationQueue = data["isOpeningConfirmationQueue"] as? Bool ?? false
        let isOpeningOrderPage = data["isOpeningOrderPage"] as? Bool ?? false

        if let routeKind = NotificationInboxRoute.Kind(rawValue: routeKindRaw), routeKind != .none {
            return NotificationInboxRoute(
                kind: routeKind,
                roomId: roomId.isEmpty ? nil : roomId,
                postcardId: postcardId.isEmpty ? nil : postcardId,
                orderId: orderId.isEmpty ? nil : orderId,
                isOpeningConfirmationQueue: isOpeningConfirmationQueue,
                isOpeningOrderPage: isOpeningOrderPage
            )
        }

        return resolveFallbackRoute(
            type: fallbackType,
            roomId: roomId.isEmpty ? nil : roomId,
            postcardId: postcardId.isEmpty ? nil : postcardId,
            orderId: orderId.isEmpty ? nil : orderId
        )
    }

    /// Fallback route mapping used when backend route fields are absent.
    /// - Parameters:
    ///   - type: Event type payload value.
    ///   - roomId: Parsed room id if present.
    ///   - postcardId: Parsed postcard id if present.
    ///   - orderId: Parsed order id if present.
    /// - Returns: Best-effort route metadata.
    private func resolveFallbackRoute(
        type: String,
        roomId: String?,
        postcardId: String?,
        orderId: String?
    ) -> NotificationInboxRoute {
        if let roomId, roomId.isEmpty == false {
            return NotificationInboxRoute(
                kind: .room,
                roomId: roomId,
                postcardId: nil,
                orderId: nil,
                isOpeningConfirmationQueue: type.hasPrefix("raid_confirmation"),
                isOpeningOrderPage: false
            )
        }

        if let postcardId, postcardId.isEmpty == false {
            return NotificationInboxRoute(
                kind: .postcard,
                roomId: nil,
                postcardId: postcardId,
                orderId: orderId,
                isOpeningConfirmationQueue: false,
                isOpeningOrderPage: type.hasPrefix("postcard_")
            )
        }

        return NotificationInboxRoute(
            kind: .none,
            roomId: nil,
            postcardId: nil,
            orderId: nil,
            isOpeningConfirmationQueue: false,
            isOpeningOrderPage: false
        )
    }

    /// Marks one remote event document as read.
    /// - Parameters:
    ///   - itemId: Event document id.
    ///   - isRead: Read state to persist.
    private func updateReadState(itemId: String, isRead: Bool) async {
        guard let currentUserId, currentUserId.isEmpty == false else { return }
        let documentRef = db.collection("users")
            .document(currentUserId)
            .collection("events")
            .document(itemId)

        do {
            try await documentRef.setData([
                "isRead": isRead,
                "readAt": isRead ? FieldValue.serverTimestamp() : NSNull(),
                "updatedAt": FieldValue.serverTimestamp()
            ], merge: true)
        } catch {
            // Keep optimistic local state even if remote update fails.
        }
    }

    /// Marks multiple event documents as read using one write batch.
    /// - Parameter itemIds: Target event document ids.
    private func markItemsAsRead(itemIds: [String]) async {
        guard let currentUserId, currentUserId.isEmpty == false else { return }
        guard itemIds.isEmpty == false else { return }

        let batch = db.batch()
        for itemId in itemIds {
            let documentRef = db.collection("users")
                .document(currentUserId)
                .collection("events")
                .document(itemId)
            batch.setData([
                "isRead": true,
                "readAt": FieldValue.serverTimestamp(),
                "updatedAt": FieldValue.serverTimestamp()
            ], forDocument: documentRef, merge: true)
        }

        do {
            try await batch.commit()
        } catch {
            // Keep optimistic local state even if remote batch update fails.
        }
    }

    /// Resolves normalized string payload from primary/secondary keys.
    /// - Parameters:
    ///   - userInfo: APNs custom payload dictionary.
    ///   - primaryKey: Preferred payload key.
    ///   - secondaryKey: Fallback payload key.
    /// - Returns: Non-empty value when available.
    private func resolvedStringValue(
        from userInfo: [AnyHashable: Any],
        primaryKey: String,
        secondaryKey: String
    ) -> String? {
        let rawValue = (userInfo[primaryKey] as? String ?? userInfo[secondaryKey] as? String ?? "")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if rawValue.isEmpty {
            return nil
        }
        return rawValue
    }
}
